server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/animeflix_catalog
      auto-index-creation: true
    redis:
      url: ${REDIS_URL:rediss://default:gQAAAAAAAf4YAAIgcDFjYzVhM2RmYWU2YTk0MGU4OTQwZDk0NTQ2MmJjODNmNg@primary-buffalo-130584.upstash.io:6379}
#      url: redis://localhost:6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: NewEpisodeEvent:com.animeflix.animecatalogservice.DTO.kafka.NewEpisodeEvent
        # Thời gian tối đa cho phép block luồng để đợi Kafka (Giảm từ 60s xuống 2s)
        max.block.ms: 2000
        # Thời gian tối đa để Network Client cố gắng kết nối (2s)
        request.timeout.ms: 2000
        # Thời gian chờ phản hồi tối đa từ Broker
        delivery.timeout.ms: 4000
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
app:
  cache:
    anime-detail-ttl: 86400
    list-ttl: 3600
logging:
  level:
    root: INFO
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
    com.animeflix: DEBUG