server:
  port: 8081

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/animeflix_user
      auto-index-creation: true
    redis:
    #      url: redis://localhost:6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-service-notifications
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.animeflix.userservice.dto.kafka,com.animeflix.animecatalogservice.DTO.kafka

  codec:
    http:
      legacy:
        response:
          write-content-length: false

# Cấu hình URL cho WebClientConfig nạp vào (Bắt buộc giữ để WebClient chạy được)
services:
  anime-catalog:
    url: ${ANIME_CATALOG_URL:http://localhost:8080}
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8085}

# Đồng bộ cấu hình log sạch sẽ, không lo bị ngập log rác
logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    com.animeflix: DEBUG